### ISSUE TITLE
Can the `pnpm-lock.yml` be remove from this template?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-themes/docus-docs-starter#12]
In fact, a new project will ask the user to install dependencies with `npm`, `yarn` or `pnpm` so I think this `pnpm-lock`.yml is completely useless.

**Comment by Atinux** [comment]
Agree we should not have the lock file in it.

**Comment by Atinux** [comment]
Happy to open a PR?

**Comment by Barbapapazes** [comment]
Yes!
